// <auto-generated />
using System;
using DataExportPlatform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataExportPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataExportPlatform.Core.Models.Accessright", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Code").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<int>("EmployeeId").HasColumnType("int");
                b.HasKey("Id");
                b.ToTable("Accessrights");
            });

            modelBuilder.Entity("DataExportPlatform.Core.Models.Costcenter", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Code").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("ResponsibleEmail").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.HasKey("Id");
                b.ToTable("Costcenters");
            });

            modelBuilder.Entity("DataExportPlatform.Core.Models.CostcenterResponsibleOverride", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("ChangedAt").HasColumnType("datetime2");
                b.Property<string>("ChangedBy").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<int>("CostcenterId").HasColumnType("int");
                b.Property<string>("Reason").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<string>("ResponsibleUserEmail").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.HasKey("Id");
                b.ToTable("CostcenterResponsibleOverrides");
            });

            modelBuilder.Entity("DataExportPlatform.Core.Models.Employee", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("CostcenterId").HasColumnType("int");
                b.Property<string>("DepartmentCode").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Id");
                b.ToTable("Employees");
            });

            modelBuilder.Entity("DataExportPlatform.Core.Models.ExportLog", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("AppId").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("ErrorMessage").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                b.Property<DateTime>("ExportedAt").HasColumnType("datetime2");
                b.Property<string>("FileName").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<long>("FileSizeBytes").HasColumnType("bigint");
                b.Property<int>("PipelineRunId").HasColumnType("int");
                b.Property<int>("RecordCount").HasColumnType("int");
                b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.HasIndex("PipelineRunId");
                b.ToTable("ExportLogs");
            });

            modelBuilder.Entity("DataExportPlatform.Core.Models.PipelineRun", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ErrorMessage").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                b.Property<DateTime?>("FinishedAt").HasColumnType("datetime2");
                b.Property<DateTime>("StartedAt").HasColumnType("datetime2");
                b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.ToTable("PipelineRuns");
            });

            modelBuilder.Entity("DataExportPlatform.Core.Models.ExportLog", b =>
            {
                b.HasOne("DataExportPlatform.Core.Models.PipelineRun", "PipelineRun")
                    .WithMany("ExportLogs")
                    .HasForeignKey("PipelineRunId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("PipelineRun");
            });

            modelBuilder.Entity("DataExportPlatform.Core.Models.PipelineRun", b =>
            {
                b.Navigation("ExportLogs");
            });
#pragma warning restore 612, 618
        }
    }
}
